const Images : { [key: string]: any }= {
    image1: require('../DrinksImg/cubalibre.png'),
    image2: require('../DrinksImg/whiterussian.png'),
    image3: require('../DrinksImg/blackrussian.png'),
    image4: require('../DrinksImg/mojito.png'),
    image5: require('../DrinksImg/cosmopolitan.png'),
    image6: require('../DrinksImg/negroni.png'),
    image7: require('../DrinksImg/sexonthebeach.png'),
    image8: require('../DrinksImg/aperolspritz.png'),
    image9: require('../DrinksImg/tomcollins.png'),
    image10: require('../DrinksImg/moscowmule.png'),
    image11: require('../DrinksImg/jagerbomb.png'),
    image12: require('../DrinksImg/tequilasunrise.png'),
    image13: require('../DrinksImg/longislandicedtea.png'),
    image14: require('../DrinksImg/krwawamary.png'),
    image15: require('../DrinksImg/martini.png'),
    image16: require('../DrinksImg/pornstarmartini.png'),
    image17: require('../DrinksImg/oldfashioned.png'),
    image18: require('../DrinksImg/whiskysour.png'),
    image19: require('../DrinksImg/margarita.png'),
    image20: require('../DrinksImg/caipirinia.png'),
    image21: require('../DrinksImg/vespermartin.png'),
    image22: require('../DrinksImg/manhattan.png'),
    image23: require('../DrinksImg/daiquiri.png'),
    image24: require('../DrinksImg/basilsmash.png'),
    image25: require('../DrinksImg/darknstormy.png'),
    image26: require('../DrinksImg/zombie.png'),
    image27: require('../DrinksImg/amarettosour.png'),
    image28: require('../DrinksImg/cloverclub.png'),
    image29: require('../DrinksImg/americano.png'),
    image30: require('../DrinksImg/maitai.png'),
    image31: require('../DrinksImg/paloma.png'),
    image32: require('../DrinksImg/penicylina.png'),
    image33: require('../DrinksImg/drymartini.png'),
    image34: require('../DrinksImg/espressomartini.png'),
    image35: require('../DrinksImg/french75.png'),
    image36: require('../DrinksImg/pinacolada.png'),
    image37: require('../DrinksImg/dirtymartini.png')
};

export default Images;